name: Flutter Auto Upgrade

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: '0 0 * * 1'   # every Monday

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Flutter (latest)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable   # always latest stable

      # 3. Check version
      - name: Flutter version
        run: flutter --version

      # 4. Upgrade dependencies
      - name: Upgrade dependencies
        run: flutter pub upgrade --major-versions

      # 5. Analyze code
      - name: Analyze
        run: flutter analyze

      # 6. Run tests
      - name: Run tests
        run: flutter test

      # 7. Commit changes (IMPORTANT)
      - name: Commit changes
        run: |
          git config --global user.name "FlutterSanjay" 
          git config --global user.email "sanjayshaw80138@gmail.com" 
          git add .
          git commit -m "Auto upgrade Flutter SDK & dependencies" || echo "No changes"
          git push
